### ISSUE TITLE
Add option to store SSH key contents as a variable

### ISSUE THREAD

**Issue by attila** [Stouts/Stouts.jenkins#31]
First of all, I'm a fan of this ansible role already, thanks for this.

It would be nice to be able to specify the contents of the SSH key in a variable so that it can be stored in an yml encrypted with ansible-vault. Maybe as an option to specify either the file or the contents of the file?

**Comment by klen** [comment]
Thank you, maybe this is kind a too late but it's possible to do for latest versions.
