### ISSUE TITLE
Multiple handlers with same name don't work with later Ansible versions

### ISSUE THREAD

**Issue by efine** [Stouts/Stouts.jenkins#38]
Ref to [discussion with mpdehaan](https://groups.google.com/d/msg/ansible-project/qtyWGOQN3O8/uPpMr0LpsD8J).

I'm using Ansible v1.9.0.1.

Errors are occurring after restart handler is called. Looking into the handlers, I see multiple handlers with the same name. Although this might have worked at one time, it seems as if it's unsupported and may not work any more. I think it may be necessary to name them differently and chain them manually as shown in the above-mentioned discussion.

~~~
NOTIFIED: [Stouts.jenkins | jenkins restart] ********************************** 
changed: [jenkins.example.com]

NOTIFIED: [Stouts.jenkins | jenkins reload configuration] ********************* 
failed: [jenkins.example.com] => {"changed": true, "cmd": ["java", "-jar", "/var/lib/jenkins/jenkins-cli.jar", "-noKeyAuth", "-s", "http://jenkins.example.com:8080/", "reload-configuration"], "delta": "0:00:00.285201", "end": "2015-07-21 17:56:28.045029", "rc": 1, "start": "2015-07-21 17:56:27.759828", "warnings": []}
stderr: Exception in thread "main" java.io.IOException: Failed to connect to http://jenkins.example.com:8080/
...
~~~

**Comment by pangkalizer** [comment]
same here.. raised PR #39 with some other stuffs

**Comment by klen** [comment]
Looks like it is fixed already.
