### ISSUE TITLE
Unable to find OS specific variables for Ubuntu Wily

### ISSUE THREAD

**Issue by farridav** [Stouts/Stouts.jenkins#49]
Hi, 

Im getting:

```
fatal: [tooling-live] => input file not found at [...]/Stouts.jenkins/vars/Debian-wily.yml or [...]/Debian-wily.yml
```
When trying to run against my Ubuntu Wily box AWS  ami id: `ami-9d9926ee`  perhaps you could default the vars file used with smth like:

```
  with_first_found:
    - files:
       - {{ ansible_distribution }}.yml
       - default.yml
```
in https://github.com/Stouts/Stouts.jenkins/blob/develop/tasks/main.yml#L7

Ive manually changed the role to point to `Debian-wheezy.yml` and the role works as expected...

Thanks

**Comment by klen** [comment]
Thank you for the report!
